version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: enterprise-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: enterprise-zipkin
    ports:
      - "9411:9411"
    restart: unless-stopped

volumes:
  mongodb_data:
