server:
  port: 8081

spring:
  application:
    name: basic-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/enterprise_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
